### ISSUE TITLE
Create TWI binary mask fails - due to NaN?

### ISSUE THREAD

**Issue by j08lue** [GlobWetlandAfricaIII/GWA_scripts#15]
Seems like the comparison in this line fails when there are NaN

https://github.com/GlobWetlandAfrica/GWA_scripts/blob/c10f2989e75817e9cc620ef01cea155c1e07e68f/scripts/GWA_TBX/WI_WCR/04_WIWCR_TWIBinaryMask.py#L78

But that is actually unlikely, because numpy usually just raises a `RuntimeWarning`.

Needs further investigation.

**Comment by redfrexx** [comment]
true it's usually just a `RuntimeWarning `. I'll look into it.

**Comment by j08lue** [comment]
It might also be that this was the last message we saw before the script crashed due to other reasons. I just saw the error on @ctottrup's machine, have not tried to reproduce it yet. Fact is that the output was not created...

**Comment by redfrexx** [comment]
I wasen't able to reproduce this error so far even if the TWI raster contained NAN values. Which AOI did you use for the calculation, @ctottrup ?

**Comment by j08lue** [comment]
Let's revisit this if someone else encounters this issue.
