### ISSUE TITLE
Advanced parameters in R scripts

### ISSUE THREAD

**Issue by radosuav** [GlobWetlandAfricaIII/GWA_scripts#28]
@j08lue @redfrexx @kegro @sun0601 

I have just added the missing functionality to set R parameters as advanced (see https://github.com/TIGER-NET/WOIS_processing/commit/2b1e38657f030fc98a189c9e6f58e7f696587144). Please update your Processing plugin located in C:\Users\user_name\.qgis2\python\plugins\ with the version from https://github.com/TIGER-NET/WOIS_processing (you can use "Clone or download" button).

To set the parameter as advanced you have to use “advanced” keyword in the input parameter description at the top of the R script. It can be used in combination with “optional” key word by separating them with comma and no spaces, i.e. “advanced,optional”.

So the following are correct:
##Start_Date=optional string
##Start_Date=optional,advanced string
##Start_Date=advanced,optional string
##Start_Date=advanced string
##Start_Date=string

Please let me know if you encounter any problems.

**Comment by j08lue** [comment]
Thanks, @radosuav . Will you submit this to the QGIS upstream, too?

**Comment by radosuav** [comment]
Yes, I'll just wait a couple of days for bug reports ;)

**Comment by radosuav** [comment]
QGIS developers did not accept this change, since it was classified as a feature and not a bug fix and therefore not suitable for merging to LTR. So we have to be careful when updating Processing to make sure that this change does not get lost.

**Comment by radosuav** [comment]
@j08lue @redfrexx @kegro @sun0601 Could you please set the advanced parameters in your R scripts by the 7th of September.
