### ISSUE TITLE
High memory usage when running WHM_NDVIstatistics.rsx

### ISSUE THREAD

**Issue by radosuav** [GlobWetlandAfricaIII/GWA_scripts#29]
A user has reported running out of memory when executing [WHM_NDVIstatistics.rsx](https://github.com/GlobWetlandAfrica/GWA_scripts/blob/master/rscripts/GWA_TBX/WHM_NDVIstatistics.rsx) with 7 S2 scenes as input. His computer has 16 GB of RAM and the error message is in the attached screenshot.

@sun0601 could you please try to refactor [WHM_NDVIstatistics.rsx](https://github.com/GlobWetlandAfrica/GWA_scripts/blob/master/rscripts/GWA_TBX/WHM_NDVIstatistics.rsx) to use less memory. 
From a quick scan of the code there are two good places to start: 
- Do not save all the input images in [rast.list](https://github.com/GlobWetlandAfrica/GWA_scripts/blob/master/rscripts/GWA_TBX/WHM_NDVIstatistics.rsx#L14) since they are not used anywhere after the [for loop](https://github.com/GlobWetlandAfrica/GWA_scripts/blob/master/rscripts/GWA_TBX/WHM_NDVIstatistics.rsx#L18). Inside the for loop the input image could be used directly, e.g.
```R
data<-stack(img[i])
band3=subset(data, 3)
band7=subset(data, 7)
```
- Convert NDVI to integer as soon as [it is calculated](https://github.com/GlobWetlandAfrica/GWA_scripts/blob/master/rscripts/GWA_TBX/WHM_NDVIstatistics.rsx#L23), i.e.
```R
ndvi[i]<-as.integer((band7-band3)/(band7+band3)*1000)
```
![error](https://user-images.githubusercontent.com/4759850/44029425-922a8c58-9efd-11e8-8053-c47703ddd237.JPG)

**Comment by sun0601** [comment]
I change the algorithm to call r.series in python to calculate temporal statistics. No need to recalculate NDVI after calculating NDVI in the previous step. Can be applied to other indices as well.
