### ISSUE TITLE
Move WOIS scripts into GWA Toolbox.

### ISSUE THREAD

**Issue by radosuav** [GlobWetlandAfricaIII/GWA_scripts#30]
WOIS scripts which are used in GWA Toolbox need to be moved over, since we decided to not include WOIS as part of GWA Toolbox. 

Most of the scripts were moved in 526c9cd0fdccf1b2ab66105823133a151583f1cb and c6a2156a8753695237a079547c2003b8fa23e89b. As far as I can tell only two are missing:
* dhigras:atmosphericcorrection - @j08lue do you know where I can find it
* wg9hm:12getfewsrfedataosfwf - it will probably be added to budyko-qgis since it is required for downloading rainfall data used in the hydrological model

**Comment by j08lue** [comment]
`dhigras:atmosphericcorrection` is a stripped-down version of our old 6S atmospheric correction wrapper as a QGIS plugin - actually without the 6S capabilities, so only dark object subtraction, I think.

You can find it here: https://github.com/TIGER-NET/WOIS_plugins/tree/master/atmospheric_correction, which is a copy of https://github.com/DHI-GRAS/atmcorr/tree/gwa_dist

It would be great to distribute the full version including 6S, but that would require some hacking to install Py6S including the 6S binaries in QGIS Python, so I guess we have to stick to the simple version for now.

**Comment by j08lue** [comment]
@radosuav I see you already got quite far with this endeavour - merging WOIS_scripts into GWA_scripts. What is the status?

Why did you not add https://github.com/DHI-GRAS/swi-downloader (which was a submodule in https://github.com/TIGER-NET/WOIS_scripts/tree/master/scripts)? Is that not needed in GWA? I have not tested it in a while and don't know whether it works...

**Comment by radosuav** [comment]
Looking at the QGIS log messages when the toolbox is first loaded (QGIS is opened) it seems that all the scripts are there except for dhigras:atmosphericcorrection and wg9hm:12getfewsrfedataosfwf:
![image](https://user-images.githubusercontent.com/4759850/45874123-60b3b680-bd94-11e8-97ba-9545646cd6ee.png)

I am not sure which workflow uses SWI downloader. @ctottrup, do you know if this downloader is used anywhere?

**Comment by j08lue** [comment]
Thanks for checking, @radosuav. I suggest we just add the SWI download script for now and do a cleanup later when the merging of WOIS and GWA is complete.

By the way, the atmospheric correction plugin now lives here: https://github.com/GlobWetlandAfrica/simple-atmospheric-correction

**Comment by j08lue** [comment]
And I added the plugin as a submodule to https://github.com/GlobWetlandAfrica/GWA_plugins
