### ISSUE TITLE
scripts of the IR and WI-workflows expect fmask output in S2 product folder

### ISSUE THREAD

**Issue by j08lue** [GlobWetlandAfricaIII/GWA_scripts#34]
PR #27 wanted to change the Fmask script interface such that output from Fmask is always stored in the S2 product folder. 

I rejected that change because of [interface design concerns](https://github.com/GlobWetlandAfrica/GWA_scripts/pull/27#issuecomment-423473024).

However, according to @bjoern234, some of the IR and WI scripts depend on this behavior (see https://github.com/GlobWetlandAfrica/GWA_scripts/pull/27#issuecomment-423506198).

**Comment by j08lue** [comment]
@bjoern234, to ease the stress before the weekend, we will include the version of the QGIS Fmask scripts from [your pull request](https://github.com/DHI-GRAS/qgis-python-fmask/pull/1) with this weekend's beta release.

However, after that, I would like to ask you to find a different solution.

The simplest solution for you would be to just create a new QGIS script and add it to this repo that wraps the QGIS Fmask script, basically just modifying the interface a bit:

```python
#Definition of inputs and outputs
#==================================
##FMask-geoville=group
##FMask Sentinel 2 geoville=name
##ParameterFile|granuledir|Image Directory (For images including subimages use target granule directory)|True|False
##ParameterFile|anglesfile|Input angles file containing satellite and sun azimuth and zenith|False|True|
##ParameterNumber|mincloudsize|Mininum cloud size (in pixels) to retain, before any buffering|0|None|0
##ParameterNumber|cloudbufferdistance|Distance (in metres) to buffer final cloud objects|0|None|150
##ParameterNumber|shadowbufferdistance|Distance (in metres) to buffer final cloud shadow objects|0|None|300
##ParameterNumber|cloudprobthreshold|Cloud probability threshold (percentage) (Eqn 17)|0|100|20
##*ParameterNumber|nirsnowthreshold|Threshold for NIR reflectance for snow detection (Eqn 20). Increase this to reduce snow commission errors|0|1|0.11
##*ParameterNumber|greensnowthreshold|Threshold for Green reflectance for snow detection (Eqn 20). Increase this to reduce snow commission errors|0|1|0.1

dirs = [x[0] for x in os.walk(granuledir)]
for dir in dirs:
    if 'IMG_DATA' in dir:
        scene = os.path.basename(glob(os.path.join(dir, '*.jp2'))[0])[:-8]
outpath = os.path.join(dir, scene + '_fmask.tif')

processing.runalg(
        "script:fmasksentinel2",
        granuledir,
        anglesfile,
        outpath,
        all,
        the,
        other,
        parameters
)
```

Then you can link to that script instead in your workflows and you are good to go.

What do you think?

**Comment by bjoern234** [comment]
@j08lue 
ok! We will implement this next week
