### ISSUE TITLE
WI / WCR Calculation of Indices: Import Error: No module named bottleneck

### ISSUE THREAD

**Issue by redfrexx** [GlobWetlandAfricaIII/GWA_scripts#5]
I just realized that the python package bottleneck is not included in qgis by default, which is why the calculation of the spectral indices for the WI and WCR modules fails.

Can you add bottleneck to the GWA installer? Otherwise I will just repalce the bottleneck functions with numpy functions.

**Comment by j08lue** [comment]
Cool you are using `bottleneck` and I will add it to the installer package next time I update it.

But in [the single operation where you are using it](https://github.com/GlobWetlandAfricaIII/GWA_scripts/blob/39ed2647b1db3684dc6578f1ec790edc58fc7143/scripts/GWA_TBX/WI_WCR/data/python/RSutils/RSutils.py#L172), I think you should replace it with `np.nansum` anyways. As far as I understand, this operation is not repeated very often (like in a very fast loop), so it is not really a "bottleneck" for performance. Better to keep the number of dependencies down in case someone installs the scripts who does not have the full package for some reason.

**Comment by redfrexx** [comment]
Ah yes you're right, there's just one occurrence of bottleneck in that script anyways. I'll replace it. Thanks!
