### ISSUE TITLE
Fmask fails if file path is too long

### ISSUE THREAD

**Issue by redfrexx** [GlobWetlandAfricaIII/GWA_scripts#7]
Fmask for Sentinel-2 scenes fails if the file path is too long. 

This error might be avoided by shortening the file path using win32api.GetShortPathName in Python, but I think this also won't work if the scene is stored on a network drive instead of a local drive.

**Comment by j08lue** [comment]
**Windows** fails when the file path is too long. Not much to do about this I am afraid.

**Comment by j08lue** [comment]
Are you okay with this admittedly unsatisfactory resolution, @redfrexx?

**Comment by redfrexx** [comment]
I think we can close this issue.
